Add 'attribute' to allowed mapping config types
symfony/doctrine-bridge pull request #10
Opened 2021-03-25 08:24 UTC by L41rx

Hi! Recently https://github.com/doctrine/orm/pull/8266 was merged in. I had made a new symfony project and wanted to use the entity attributes to generate a schema, I was able to do so but needed to allow setting a type of "attribute" in my doctrine orm mappings type configuration by changing this class 
(and adding the corresponding parameter for the attributes driver to DoctrineBundle (https://github.com/doctrine/DoctrineBundle/pull/1313)

I am not sure if this is useful, sorry if it is not! (I am not sure which branch this should go to, because I guess this relies on doctrine/orm 2.9.x)

thanks for all the code by the way!

2021-03-25 17:18 UTC, dunglas requested changes
LGTM except the exception message.

2021-03-25 17:18 UTC, dunglas commented on DependencyInjection/AbstractDoctrineExtension.php
>              throw new \InvalidArgumentException(sprintf('Can only configure "xml", "yml", "annotation", "php" or "staticphp" through the DoctrineBundle. Use your own bundle to configure other metadat
```suggestion
            throw new \InvalidArgumentException(sprintf('Can only configure "xml", "yml", "annotation", "php" or "staticphp", "attribute" through the DoctrineBundle. Use your own bundle to configure other metadata drivers. You can register them by adding a new driver to the "%s" service definition.', $this->getObjectManagerElementName($objectManagerName.'_metadata_driver')));
```

2021-03-26 14:48 UTC, L41rx commented
> 
> 
> LGTM except the exception message.

thx! missed it

2021-03-26 15:20 UTC, dunglas approved these changes

2021-04-14 17:20 UTC, nicolas-grekas commented
Closing, as explained by the bot.
Coincidentally, this has now been proposed at https://github.com/symfony/symfony/pull/40793
Thanks for submitting.

2021-04-14 17:20 UTC, closed without merging